name: ci
on  : [push, pull_request]

jobs:

  linux-stable:

    name: Linux Rust Stable
    runs-on: ubuntu-latest

    steps:

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly


      - name: Checkout crate
        uses: actions/checkout@v2


      - name: Run tests
        run: bash ci/test.bash


      - name: Build documentation
        run: bash ci/doc.bash


      - name: Check coverage
        run: bash ci/coverage.bash


  linux-nightly:

    name: Linux Rust Nightly
    runs-on: ubuntu-latest

    steps:

      - name: Install latest nightly Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: clippy


      - name: Checkout crate
        uses: actions/checkout@v2


      - name: Run tests
        run : bash ci/test.bash


      - name: Run clippy
        run : bash ci/clippy.bash


      - name: Build documentation
        run : bash ci/doc.bash


